$schema: "https://raw.githubusercontent.com/rainbowdashlabs/krile/main/.github/tag_schema.json"

directory: "tags"
category: ["test", "random"]
exclude: ["ignored_tag"]
public: true
language: "en"
name: Krile Test Repository
description: A repository for testing of bot functionality.

